// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportColorDetailPDF(arg1) {
  return window['go']['main']['App']['ExportColorDetailPDF'](arg1);
}

export function ExportComparisonPDF(arg1) {
  return window['go']['main']['App']['ExportComparisonPDF'](arg1);
}

export function ExportPaintByNumbersPDF(arg1) {
  return window['go']['main']['App']['ExportPaintByNumbersPDF'](arg1);
}

export function GetAspectRatio() {
  return window['go']['main']['App']['GetAspectRatio']();
}

export function GetMixingRecipe(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetMixingRecipe'](arg1, arg2, arg3);
}

export function GetNColors() {
  return window['go']['main']['App']['GetNColors']();
}

export function GetPaintInventory() {
  return window['go']['main']['App']['GetPaintInventory']();
}

export function GetPaintMatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetPaintMatch'](arg1, arg2, arg3);
}

export function GetPosterizeMode() {
  return window['go']['main']['App']['GetPosterizeMode']();
}

export function GetRecentImages() {
  return window['go']['main']['App']['GetRecentImages']();
}

export function GetSmoothingPasses() {
  return window['go']['main']['App']['GetSmoothingPasses']();
}

export function GetTileSize() {
  return window['go']['main']['App']['GetTileSize']();
}

export function GetWindowSettings() {
  return window['go']['main']['App']['GetWindowSettings']();
}

export function PickColorFromCoordinates(arg1, arg2, arg3) {
  return window['go']['main']['App']['PickColorFromCoordinates'](arg1, arg2, arg3);
}

export function ProcessImage(arg1) {
  return window['go']['main']['App']['ProcessImage'](arg1);
}

export function ReprocessImage() {
  return window['go']['main']['App']['ReprocessImage']();
}

export function SaveWindowSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveWindowSettings'](arg1, arg2, arg3, arg4);
}

export function SetAspectRatio(arg1) {
  return window['go']['main']['App']['SetAspectRatio'](arg1);
}

export function SetNColors(arg1) {
  return window['go']['main']['App']['SetNColors'](arg1);
}

export function SetPosterizeMode(arg1) {
  return window['go']['main']['App']['SetPosterizeMode'](arg1);
}

export function SetSmoothingPasses(arg1) {
  return window['go']['main']['App']['SetSmoothingPasses'](arg1);
}

export function SetTileSize(arg1) {
  return window['go']['main']['App']['SetTileSize'](arg1);
}
