// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {inventory} from '../models';

export function ExportColorDetailPDF(arg1:main.PDFExportData):Promise<void>;

export function ExportComparisonPDF(arg1:main.ComparisonPDFData):Promise<void>;

export function ExportPaintByNumbersPDF(arg1:main.PaintByNumbersPDFData):Promise<void>;

export function GetAspectRatio():Promise<string>;

export function GetMixingRecipe(arg1:number,arg2:number,arg3:number):Promise<Array<main.MixingPart>>;

export function GetNColors():Promise<number>;

export function GetPaintInventory():Promise<Array<inventory.PaintProduct>>;

export function GetPaintMatch(arg1:number,arg2:number,arg3:number):Promise<Array<main.PaintMatch>>;

export function GetPosterizeMode():Promise<boolean>;

export function GetRecentImages():Promise<Array<main.RecentImageInfo>>;

export function GetSmoothingPasses():Promise<number>;

export function GetTileSize():Promise<number>;

export function GetWindowSettings():Promise<main.WindowSettings>;

export function PickColorFromCoordinates(arg1:number,arg2:number,arg3:number):Promise<Array<main.PaintMatch>>;

export function ProcessImage(arg1:string):Promise<main.ProcessingResult>;

export function ReprocessImage():Promise<void>;

export function SaveWindowSettings(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SetAspectRatio(arg1:string):Promise<void>;

export function SetNColors(arg1:number):Promise<void>;

export function SetPosterizeMode(arg1:boolean):Promise<void>;

export function SetSmoothingPasses(arg1:number):Promise<void>;

export function SetTileSize(arg1:number):Promise<void>;
